"""
HTML report generator for asset-lens.
HTML 报告生成模块
"""

from typing import Any


class HTMLReportGenerator:
    """HTML 报告生成器"""

    def generate_html(self, report: dict[str, Any], include_charts: bool = True) -> str:
        """生成 HTML 内容"""
        report_type = report.get("report_type", "unknown")
        title = self._get_report_title(report_type)

        html_parts = [
            "<!DOCTYPE html>",
            "<html lang='zh-CN'>",
            "<head>",
            "    <meta charset='UTF-8'>",
            "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
            f"    <title>{title} - Asset Lens</title>",
            "    <style>",
            "        * { margin: 0; padding: 0; box-sizing: border-box; }",
            "        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; }",
            "        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }",
            "        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }",
            "        .header h1 { font-size: 28px; margin-bottom: 10px; }",
            "        .header .meta { font-size: 14px; opacity: 0.9; }",
            "        .card { background: white; border-radius: 10px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }",
            "        .card h2 { font-size: 20px; margin-bottom: 15px; color: #667eea; border-bottom: 2px solid #667eea; padding-bottom: 10px; }",
            "        .card h3 { font-size: 16px; margin: 15px 0 10px 0; color: #333; }",
            "        .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }",
            "        .metric { background: #f8f9fa; padding: 15px; border-radius: 8px; text-align: center; }",
            "        .metric .value { font-size: 24px; font-weight: bold; color: #667eea; }",
            "        .metric .label { font-size: 12px; color: #666; margin-top: 5px; }",
            "        .warning { background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 10px 0; border-radius: 4px; }",
            "        .warning.high { background: #f8d7da; border-left-color: #dc3545; }",
            "        .recommendation { background: #d1ecf1; border-left: 4px solid #17a2b8; padding: 15px; margin: 10px 0; border-radius: 4px; }",
            "        table { width: 100%; border-collapse: collapse; margin: 15px 0; }",
            "        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }",
            "        th { background: #f8f9fa; font-weight: 600; }",
            "        tr:hover { background: #f8f9fa; }",
            "        .positive { color: #28a745; }",
            "        .negative { color: #dc3545; }",
            "        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }",
            "    </style>",
            "</head>",
            "<body>",
            "    <div class='container'>",
            "        <div class='header'>",
            f"            <h1>📊 {title}</h1>",
            f"            <div class='meta'>生成时间: {report.get('generate_time', 'N/A')}</div>",
            "        </div>",
        ]

        if report_type == "strategy_report":
            html_parts.extend(self._generate_strategy_html(report))
        elif report_type == "pool_report":
            html_parts.extend(self._generate_pool_html(report))
        elif report_type == "comparison_report":
            html_parts.extend(self._generate_comparison_html(report))
        elif report_type == "risk_report":
            html_parts.extend(self._generate_risk_html(report))

        html_parts.extend(
            [
                "        <div class='footer'>",
                "            <p>Generated by Asset Lens - Personal Asset Operating System</p>",
                "        </div>",
                "    </div>",
                "</body>",
                "</html>",
            ]
        )

        return "\n".join(html_parts)

    def _get_report_title(self, report_type: str) -> str:
        """获取报告标题"""
        titles = {
            "strategy_report": "策略报告",
            "pool_report": "股票池报告",
            "comparison_report": "策略对比报告",
            "risk_report": "风险评估报告",
        }
        return titles.get(report_type, "投资报告")

    def _generate_strategy_html(self, report: dict[str, Any]) -> list[str]:
        """生成策略报告 HTML"""
        parts = []
        strategy_info = report.get("strategy_info", {})
        pool_status = report.get("pool_status", {})
        performance = report.get("performance", {})

        parts.extend(
            [
                "        <div class='card'>",
                "            <h2>策略信息</h2>",
                f"            <p><strong>名称:</strong> {strategy_info.get('name', 'N/A')}</p>",
                f"            <p><strong>描述:</strong> {strategy_info.get('description', 'N/A')}</p>",
                "        </div>",
                "        <div class='card'>",
                "            <h2>股票池状态</h2>",
                "            <div class='metrics'>",
                "                <div class='metric'>",
                f"                    <div class='value'>{pool_status.get('total_stocks', 0)}</div>",
                "                    <div class='label'>总股票数</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{pool_status.get('holding_count', 0)}</div>",
                "                    <div class='label'>持有中</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{pool_status.get('watching_count', 0)}</div>",
                "                    <div class='label'>观察中</div>",
                "                </div>",
                "            </div>",
                "        </div>",
                "        <div class='card'>",
                "            <h2>绩效表现</h2>",
                "            <div class='metrics'>",
                "                <div class='metric'>",
                f"                    <div class='value'>{performance.get('total_profit', 0):.2f}</div>",
                "                    <div class='label'>总收益</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{performance.get('total_profit_rate', 0):.2%}</div>",
                "                    <div class='label'>收益率</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{performance.get('win_rate', 0):.1%}</div>",
                "                    <div class='label'>胜率</div>",
                "                </div>",
                "            </div>",
                "        </div>",
            ]
        )

        if report.get("recommendations"):
            parts.append("        <div class='card'><h2>建议</h2>")
            for rec in report["recommendations"]:
                parts.append(f"            <div class='recommendation'>{rec.get('message', '')}</div>")
            parts.append("        </div>")

        return parts

    def _generate_pool_html(self, report: dict[str, Any]) -> list[str]:
        """生成股票池报告 HTML"""
        parts = []
        summary = report.get("summary", {})
        performance = report.get("performance", {})

        parts.extend(
            [
                "        <div class='card'>",
                "            <h2>概览</h2>",
                "            <div class='metrics'>",
                "                <div class='metric'>",
                f"                    <div class='value'>{summary.get('total_stocks', 0)}</div>",
                "                    <div class='label'>总股票数</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{summary.get('total_profit', 0):.2f}</div>",
                "                    <div class='label'>总收益</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{summary.get('total_profit_rate', 0):.2%}</div>",
                "                    <div class='label'>收益率</div>",
                "                </div>",
                "            </div>",
                "        </div>",
                "        <div class='card'>",
                "            <h2>表现</h2>",
                "            <div class='metrics'>",
                "                <div class='metric'>",
                f"                    <div class='value'>{performance.get('win_rate', 0):.1%}</div>",
                "                    <div class='label'>胜率</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{performance.get('avg_profit_rate', 0):.2%}</div>",
                "                    <div class='label'>平均收益</div>",
                "                </div>",
                "            </div>",
                "        </div>",
            ]
        )

        risk = report.get("risk_analysis", {})
        if risk:
            parts.extend(
                [
                    "        <div class='card'>",
                    "            <h2>风险分析</h2>",
                    f"            <p><strong>风险等级:</strong> {risk.get('risk_level', 'N/A')}</p>",
                    f"            <p>{risk.get('message', '')}</p>",
                    "        </div>",
                ]
            )

        return parts

    def _generate_comparison_html(self, report: dict[str, Any]) -> list[str]:
        """生成对比报告 HTML"""
        parts = []
        strategies = report.get("strategies", [])

        parts.extend(
            [
                "        <div class='card'>",
                "            <h2>策略对比</h2>",
                "            <table>",
                "                <thead>",
                "                    <tr>",
                "                        <th>策略</th>",
                "                        <th>股票数</th>",
                "                        <th>胜率</th>",
                "                        <th>收益率</th>",
                "                        <th>风险</th>",
                "                    </tr>",
                "                </thead>",
                "                <tbody>",
            ]
        )

        for s in strategies:
            profit_class = "positive" if s.get("total_profit_rate", 0) >= 0 else "negative"
            parts.extend(
                [
                    "                    <tr>",
                    f"                        <td>{s.get('name', '')}</td>",
                    f"                        <td>{s.get('total_stocks', 0)}</td>",
                    f"                        <td>{s.get('win_rate', 0):.1%}</td>",
                    f"                        <td class='{profit_class}'>{s.get('total_profit_rate', 0):.2%}</td>",
                    f"                        <td>{s.get('risk_level', '')}</td>",
                    "                    </tr>",
                ]
            )

        parts.extend(
            [
                "                </tbody>",
                "            </table>",
                "        </div>",
            ]
        )

        return parts

    def _generate_risk_html(self, report: dict[str, Any]) -> list[str]:
        """生成风险报告 HTML"""
        parts = []
        metrics = report.get("risk_metrics", {})

        parts.extend(
            [
                "        <div class='card'>",
                "            <h2>风险指标</h2>",
                "            <div class='metrics'>",
                "                <div class='metric'>",
                f"                    <div class='value'>{metrics.get('concentration', 0):.1%}</div>",
                "                    <div class='label'>持仓集中度</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{metrics.get('win_rate', 0):.1%}</div>",
                "                    <div class='label'>胜率</div>",
                "                </div>",
                "                <div class='metric'>",
                f"                    <div class='value'>{metrics.get('max_loss', 0):.2%}</div>",
                "                    <div class='label'>最大亏损</div>",
                "                </div>",
                "            </div>",
                "        </div>",
            ]
        )

        warnings = report.get("warnings", [])
        if warnings:
            parts.append("        <div class='card'><h2>警告</h2>")
            for w in warnings:
                level_class = "high" if w.get("level") == "high" else ""
                parts.append(f"            <div class='warning {level_class}'>{w.get('message', '')}</div>")
            parts.append("        </div>")

        recommendations = report.get("recommendations", [])
        if recommendations:
            parts.append("        <div class='card'><h2>建议</h2>")
            for rec in recommendations:
                parts.append(f"            <div class='recommendation'>{rec.get('message', '')}</div>")
            parts.append("        </div>")

        return parts
