from typing import Any


class InvestKitError(Exception):
    default_message: str
    default_code: str
    default_status_code: int
    message: str
    code: str
    status_code: int
    field: str | None
    value: Any | None
    details: dict[str, Any] | None

    def __init__(
        self,
        message: str | None = None,
        code: str | None = None,
        status_code: int | None = None,
        field: str | None = None,
        value: Any | None = None,
        details: dict[str, Any] | None = None,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...


class ValidationError(InvestKitError): ...
class NotFoundError(InvestKitError): ...
class AuthenticationError(InvestKitError): ...
class AuthorizationError(InvestKitError): ...
class RateLimitError(InvestKitError): ...
class ExternalServiceError(InvestKitError): ...
class DataError(InvestKitError): ...
class ConfigurationError(InvestKitError): ...
class CacheError(InvestKitError): ...
class DatabaseError(InvestKitError): ...
class MLModelError(InvestKitError): ...
class LLMError(InvestKitError): ...
class TradingError(InvestKitError): ...
